module.exports = (sequelize, DataTypes) => sequelize.define('AboutPage', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  hero_label: { type: DataTypes.STRING(100), defaultValue: 'Our Story' },
  hero_heading: { type: DataTypes.STRING(200), allowNull: false },
  hero_paragraph1: { type: DataTypes.TEXT, allowNull: true },
  hero_paragraph2: { type: DataTypes.TEXT, allowNull: true },
  hero_image: { type: DataTypes.STRING(500), allowNull: true },
  hero_button_text: { type: DataTypes.STRING(50), defaultValue: 'Shop Our Products' },
  hero_button_link: { type: DataTypes.STRING(200), defaultValue: '/shop' },
  vision_label: { type: DataTypes.STRING(100), defaultValue: 'Who We Are' },
  vision_subheading: { type: DataTypes.STRING(200), allowNull: true },
  vision_title: { type: DataTypes.STRING(300), allowNull: true },
  vision_body: { type: DataTypes.TEXT, allowNull: true },
  mission_title: { type: DataTypes.STRING(300), allowNull: true },
  mission_body: { type: DataTypes.TEXT, allowNull: true },
  values_label: { type: DataTypes.STRING(100), defaultValue: 'What We Stand For' },
  values_heading: { type: DataTypes.STRING(100), defaultValue: 'Our Values' },
  stats: { type: DataTypes.JSONB, defaultValue: [] },
  values: { type: DataTypes.JSONB, defaultValue: [] },
}, { tableName: 'about_page', timestamps: true, underscored: true });
