module.exports = (sequelize, DataTypes) => sequelize.define('HeroSlide', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  heading_line1: { type: DataTypes.STRING(150), allowNull: false },
  heading_line2: { type: DataTypes.STRING(150), allowNull: true },
  colored_line: { type: DataTypes.INTEGER, defaultValue: 1 },
  description_line1: { type: DataTypes.STRING(300), allowNull: false },
  description_line2: { type: DataTypes.STRING(300), allowNull: true },
  desktop_image: { type: DataTypes.STRING(500), allowNull: true },
  mobile_image: { type: DataTypes.STRING(500), allowNull: true },
  offer_label: { type: DataTypes.STRING(50), allowNull: true },
  offer_discount: { type: DataTypes.STRING(30), allowNull: true },
  offer_context_line1: { type: DataTypes.STRING(50), allowNull: true },
  offer_context_line2: { type: DataTypes.STRING(50), allowNull: true },
  coupon_code: { type: DataTypes.STRING(30), allowNull: true },
  button_text: { type: DataTypes.STRING(50), defaultValue: 'Shop Now' },
  button_link: { type: DataTypes.STRING(200), defaultValue: '/shop' },
  sort_order: { type: DataTypes.INTEGER, defaultValue: 0 },
  status: { type: DataTypes.ENUM('active', 'inactive'), defaultValue: 'active' },
}, { tableName: 'hero_slides', timestamps: true, underscored: true });
