module.exports = (sequelize, DataTypes) => sequelize.define('Order', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  order_number: { type: DataTypes.STRING(30), allowNull: false, unique: true },
  user_id: { type: DataTypes.INTEGER, allowNull: false },
  address_id: { type: DataTypes.INTEGER, allowNull: true },
  coupon_id: { type: DataTypes.INTEGER, allowNull: true },
  subtotal: { type: DataTypes.DECIMAL(12, 2), allowNull: false },
  discount_amount: { type: DataTypes.DECIMAL(12, 2), defaultValue: 0 },
  coupon_discount: { type: DataTypes.DECIMAL(12, 2), defaultValue: 0 },
  shipping_charge: { type: DataTypes.DECIMAL(10, 2), defaultValue: 0 },
  gst_amount: { type: DataTypes.DECIMAL(12, 2), defaultValue: 0 },
  total: { type: DataTypes.DECIMAL(12, 2), allowNull: false },
  status: {
    type: DataTypes.ENUM('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', 'returned', 'refunded'),
    defaultValue: 'pending',
  },
  payment_status: {
    type: DataTypes.ENUM('pending', 'paid', 'failed', 'refunded', 'partially_refunded'),
    defaultValue: 'pending',
  },
  payment_method: { type: DataTypes.ENUM('razorpay', 'cod', 'upi', 'bank_transfer'), allowNull: true },
  notes: { type: DataTypes.TEXT, allowNull: true },
  cancelled_at: { type: DataTypes.DATE, allowNull: true },
  cancel_reason: { type: DataTypes.STRING(500), allowNull: true },
  delivered_at: { type: DataTypes.DATE, allowNull: true },
  is_b2b: { type: DataTypes.BOOLEAN, defaultValue: false },
}, { tableName: 'orders', timestamps: true, underscored: true });
