module.exports = (sequelize, DataTypes) => sequelize.define('Product', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  product_id: { type: DataTypes.STRING(50), allowNull: false, comment: 'Group ID e.g. BOPP, DUCT' },
  name: { type: DataTypes.STRING(300), allowNull: false },
  slug: { type: DataTypes.STRING(350), allowNull: false, unique: true },
  category_id: { type: DataTypes.INTEGER, allowNull: false },
  brand_id: { type: DataTypes.INTEGER, allowNull: true },
  short_description: { type: DataTypes.TEXT, allowNull: true },
  long_description: { type: DataTypes.TEXT, allowNull: true },
  application: { type: DataTypes.TEXT, allowNull: true },
  key_features: { type: DataTypes.TEXT, allowNull: true },
  hsn_code: { type: DataTypes.STRING(20), allowNull: true },
  gst_percent: { type: DataTypes.DECIMAL(5, 2), defaultValue: 18.00 },
  status: { type: DataTypes.ENUM('active', 'draft', 'inactive', 'out_of_stock'), defaultValue: 'active' },
  is_featured: { type: DataTypes.BOOLEAN, defaultValue: false },
  avg_rating: { type: DataTypes.DECIMAL(3, 2), defaultValue: 0 },
  review_count: { type: DataTypes.INTEGER, defaultValue: 0 },
  view_count: { type: DataTypes.INTEGER, defaultValue: 0 },
  seo_title: { type: DataTypes.STRING(200), allowNull: true },
  seo_description: { type: DataTypes.TEXT, allowNull: true },
  seo_tags: { type: DataTypes.STRING(500), allowNull: true },
  spec_sheet: { type: DataTypes.STRING, allowNull: true },
  notes: { type: DataTypes.TEXT, allowNull: true },
}, { tableName: 'products', timestamps: true, underscored: true });
